# Generated by Django 4.2.16 on 2025-07-23 23:21

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de referencia para la categoría (máx. 255 caracteres)', max_length=255, verbose_name='Nombre interno')),
                ('title', models.CharField(blank=True, help_text='Título mostrado a los usuarios (opcional)', max_length=255, null=True, verbose_name='Título público')),
                ('description', models.TextField(help_text='Explicación detallada del propósito de esta categoría', verbose_name='Descripción')),
                ('thumbnail', models.ImageField(help_text='Imagen principal del post (se almacena en category_thumbnail_directory)', upload_to=apps.blog.models.category_thumbnail_directory, verbose_name='Imagen destacada')),
                ('slug', models.CharField(help_text='Identificador URL-amigable (máx. 128 caracteres)', max_length=128, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, help_text='Categoría superior en la jerarquía (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del post (máx. 128 caracteres)', max_length=128, verbose_name='Título')),
                ('description', models.CharField(help_text='Breve descripción del post (máx. 256 caracteres)', max_length=256, verbose_name='Descripción')),
                ('content', models.TextField(help_text='Contenido completo del post en formato HTML/Markdown', verbose_name='Contenido')),
                ('thumbnail', models.ImageField(help_text='Imagen principal del post (se almacena en blog/titulo/filename)', upload_to=apps.blog.models.blog_thumbnail_directory, verbose_name='Imagen destacada')),
                ('keywords', models.CharField(help_text='Palabras clave separadas por comas para SEO', max_length=128, verbose_name='Palabras clave')),
                ('slug', models.CharField(help_text='URL amigable para el post (máx. 128 caracteres)', max_length=128, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha automática de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha automática de última modificación', verbose_name='Última actualización')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Estado de publicación del post', max_length=10, verbose_name='Estado')),
                ('category', models.ForeignKey(help_text='Categoría temática a la que pertenece este post', on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Categoría')),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Contenido textual del título (máx. 255 caracteres)', max_length=255, verbose_name='Texto del encabezado')),
                ('slug', models.CharField(help_text='Versión URL-amigable del título (generado automáticamente)', max_length=255, verbose_name='Slug')),
                ('level', models.IntegerField(choices=[(1, 'H1 - Título principal'), (2, 'H2 - Subtítulo importante'), (3, 'H3 - Subtítulo'), (4, 'H4 - Subtítulo menor'), (5, 'H5 - Subtítulo pequeño'), (6, 'H6 - Subtítulo mínimo')], help_text='Nivel de importancia (1-6 correspondiente a h1-h6)', verbose_name='Nivel jerárquico')),
                ('order', models.PositiveIntegerField(help_text='Número que determina la posición relativa en el post', verbose_name='Orden de aparición')),
                ('post', models.ForeignKey(help_text='Post al que pertenece este encabezado', on_delete=django.db.models.deletion.PROTECT, related_name='headings', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Encabezado',
                'verbose_name_plural': 'Encabezados',
                'ordering': ['order'],
                'unique_together': {('post', 'slug'), ('post', 'order')},
            },
        ),
    ]
