# Generated by Django 4.2.16 on 2025-07-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Explicación detallada del propósito de esta categoría', null=True, verbose_name='Descripción'),
        ),
    ]
