# Generated by Django 4.2.16 on 2025-07-25 02:26

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen principal del post (se almacena en category_thumbnail_directory)', null=True, upload_to=apps.blog.models.category_thumbnail_directory, verbose_name='Imagen destacada'),
        ),
    ]
